version: "3.9"
services:
  app:
    image: xynxia/exam-app:latest
    ports:
      - "8080:80"
  api:
    image: xynxia/exam-api:latest
    ports:
      - "8081:8081"
    links:
      - mysql
    environment:
      DB_SCHEMA: 'exam'
      DB_USER: 'exam'
      DB_PASS: 'password'
      DB_PORT: '3306'
      DB_HOST: 'mysql'
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'exam'
      MYSQL_USER: 'exam'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - exam-data:/var/lib/mysql
volumes:
  exam-data:
